<?xml version="1.0" encoding="GB2312" standalone="yes"?>
<!DOCTYPE MUSIC [
<!ELEMENT MUSIC (TITLE, ARTIST, ALBUM, OFFSET, LYRICS)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT ARTIST (#PCDATA)>
<!ELEMENT ALBUM (#PCDATA)>
<!ELEMENT OFFSET (#PCDATA)>
<!ELEMENT LYRICS (LRC)*>
<!ELEMENT LRC (#PCDATA)>
<!ATTLIST LRC
TAG CDATA #REQUIRED>
]>
<MUSIC>
<TITLE>小烦恼没什么大不了（试听版）</TITLE>
<ARTIST>许嵩</ARTIST>
<ALBUM></ALBUM>
<OFFSET>0</OFFSET>
<ARTIST></ARTIST>
<LYRICS>
<LRC TAG="110">小烦恼没什么大不了（试听版）</LRC>
<LRC TAG="2870">词曲/编曲/演唱：许嵩</LRC>
<LRC TAG="16730">早晨6点不想起</LRC>
<LRC TAG="19930">睡眠太少不长命</LRC>
<LRC TAG="22780">人类应该睡到自然醒</LRC>
<LRC TAG="28550">三天两头被考评</LRC>
<LRC TAG="31760">成绩太低没自信</LRC>
<LRC TAG="34700">谁在制造这么大压力</LRC>
<LRC TAG="40490">嘿 心上人在哪里</LRC>
<LRC TAG="42970">在别人空间里</LRC>
<LRC TAG="44530">你看到他和她的合影</LRC>
<LRC TAG="46990">气 好朋友在哪里</LRC>
<LRC TAG="48970">在名品商铺里</LRC>
<LRC TAG="50590">可你却买不起</LRC>
<LRC TAG="58390">小烦恼没什么大不了</LRC>
<LRC TAG="61500">请让我看到你翘起来的嘴角</LRC>
<LRC TAG="64660">唱不了的歌就转调</LRC>
<LRC TAG="67810">千万不要自寻烦恼</LRC>
<LRC TAG="70710">小烦恼没什么大不了</LRC>
<LRC TAG="73620">请让我看到你翘起来的嘴角</LRC>
<LRC TAG="76340">不属于的就不要</LRC>
<LRC TAG="79840">快乐不靠拥有多少</LRC>
</LYRICS>
</MUSIC>