<?xml version="1.0" encoding="GB2312" standalone="yes"?>
<!DOCTYPE MUSIC [
<!ELEMENT MUSIC (TITLE, ARTIST, ALBUM, OFFSET, LYRICS)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT ARTIST (#PCDATA)>
<!ELEMENT ALBUM (#PCDATA)>
<!ELEMENT OFFSET (#PCDATA)>
<!ELEMENT LYRICS (LRC)*>
<!ELEMENT LRC (#PCDATA)>
<!ATTLIST LRC
TAG CDATA #REQUIRED>
]>
<MUSIC>
<TITLE>多余的解释</TITLE>
<ARTIST>许嵩</ARTIST>
<ALBUM></ALBUM>
<OFFSET>0</OFFSET>
<ARTIST></ARTIST>
<LYRICS>
<LRC TAG="1590">许嵩 - 多余的解释</LRC>
<LRC TAG="17760">那阵子我们的感情出了一些问题</LRC>
<LRC TAG="21410">可是我也不太清楚问题出在哪里</LRC>
<LRC TAG="25270">你面无表情的话语不剩多少意义</LRC>
<LRC TAG="29180">就当我求求你 给我一些说明</LRC>
<LRC TAG="32960">ok 我猜你只是暂时的压抑心情</LRC>
<LRC TAG="36720">不再去追问你 多给你一些关心</LRC>
<LRC TAG="40610">打电话请你去看最新的电影</LRC>
<LRC TAG="44510">你说工作很忙要加班到夜里</LRC>
<LRC TAG="47740">ooook 入冬了想给你买一条围巾</LRC>
<LRC TAG="50500">怕眼光不行所以叫着紧跟潮流的妹妹和我一起</LRC>
<LRC TAG="55960">和妹妹说说笑笑 缓释最近糟糕心绪</LRC>
<LRC TAG="59780">在下一个转角却和你相遇</LRC>
<LRC TAG="64010">她只是我的妹妹 妹妹说紫色很有韵味</LRC>
<LRC TAG="71430">她只是我的妹妹 我在担心你是否误会</LRC>
<LRC TAG="79160">她只是我的妹妹 对这个解释你无所谓</LRC>
<LRC TAG="86810">我没有思想准备 看到你身旁还有一位 不知道他是谁</LRC>
<LRC TAG="100260">那阵子我们的感情出了一些问题</LRC>
<LRC TAG="104060">可是我也不太清楚问题出在哪里</LRC>
<LRC TAG="107940">你面无表情的话语不剩多少意义</LRC>
<LRC TAG="111540">就当我求求你 给我一些说明</LRC>
<LRC TAG="115600">入冬了想给你买一条围巾</LRC>
<LRC TAG="118000">怕眼光不行所以叫着紧跟潮流的妹妹和我一起</LRC>
<LRC TAG="123200">和妹妹说说笑笑 缓释最近糟糕心绪</LRC>
<LRC TAG="127000">在下一个转角却和你相遇</LRC>
<LRC TAG="131250">她只是我的妹妹 妹妹说紫色很有韵味</LRC>
<LRC TAG="138600">她只是我的妹妹 我在担心你是否误会</LRC>
<LRC TAG="146390">她只是我的妹妹 对这个解释你无所谓</LRC>
<LRC TAG="153990">我没有思想准备 看到你身旁还有一位 不知道他是谁</LRC>
<LRC TAG="165950">紫色的围巾 交到你手里</LRC>
<LRC TAG="169710">你放进包里 说句谢谢你</LRC>
<LRC TAG="173190">要加班的你 却出现在这里</LRC>
<LRC TAG="176800">故事的结局不需要任何说明</LRC>
<LRC TAG="180670">她~~~~只是我的妹妹 妹妹说紫色很有韵味</LRC>
<LRC TAG="188360">她只是我的妹妹 我在担心你是否误会</LRC>
<LRC TAG="196360">她只是我的妹妹 对这个解释你无所谓</LRC>
<LRC TAG="204240">我没有思想准备 看到你身旁还有一位 不知道他是谁</LRC>
<LRC TAG="212030">她只是我的妹妹 妹妹说紫色很有韵味</LRC>
<LRC TAG="219360">她只是我的妹妹 我在担心你是否误会</LRC>
<LRC TAG="226970">她只是我的妹妹 对这个解释你无所谓</LRC>
<LRC TAG="234970">我没有思想准备 看到你身旁还有一位 不知道他是谁</LRC>
</LYRICS>
</MUSIC>