<?xml version="1.0" encoding="GB2312" standalone="yes"?>
<!DOCTYPE MUSIC [
<!ELEMENT MUSIC (TITLE, ARTIST, ALBUM, OFFSET, LYRICS)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT ARTIST (#PCDATA)>
<!ELEMENT ALBUM (#PCDATA)>
<!ELEMENT OFFSET (#PCDATA)>
<!ELEMENT LYRICS (LRC)*>
<!ELEMENT LRC (#PCDATA)>
<!ATTLIST LRC
TAG CDATA #REQUIRED>
]>
<MUSIC>
<TITLE>医生</TITLE>
<ARTIST>许嵩</ARTIST>
<ALBUM></ALBUM>
<OFFSET>0</OFFSET>
<ARTIST></ARTIST>
<LYRICS>
<LRC TAG="170">许嵩 - 医生</LRC>
<LRC TAG="15150">你说懂了爱不是浪漫</LRC>
<LRC TAG="22300">我的本分给你安全感</LRC>
<LRC TAG="28190">是他让你受了内伤</LRC>
<LRC TAG="32090">我努力恢复你健康</LRC>
<LRC TAG="35890">我也没那种庸俗的情节</LRC>
<LRC TAG="44230">可他还是在你心里边</LRC>
<LRC TAG="51280">偶尔梦中还窜到嘴边</LRC>
<LRC TAG="57080">其实我也能够了解</LRC>
<LRC TAG="60830">心碎一旦透过极限</LRC>
<LRC TAG="64570">有多少岁月</LRC>
<LRC TAG="67070">犹豫和不完全</LRC>
<LRC TAG="71670">我是你无奈的选择</LRC>
<LRC TAG="75020">你只想跟一个好人</LRC>
<LRC TAG="78910">我为你戴上了戒指</LRC>
<LRC TAG="82410">你的笑也还算逼真</LRC>
<LRC TAG="86010">我是你无奈的选择</LRC>
<LRC TAG="89760">却不是多么爱的人</LRC>
<LRC TAG="93350">只怪那下手太残忍</LRC>
<LRC TAG="96750">改变你一生</LRC>
<LRC TAG="113300">你说懂了爱不是浪漫</LRC>
<LRC TAG="120240">我的本分给你安全感</LRC>
<LRC TAG="126240">是他让你受了内伤</LRC>
<LRC TAG="130390">我努力恢复你健康</LRC>
<LRC TAG="134030">我也没那种庸俗的情节</LRC>
<LRC TAG="142230">可他还是在你心里边</LRC>
<LRC TAG="149330">偶尔梦中还窜到嘴边</LRC>
<LRC TAG="155320">其实我也能够了解</LRC>
<LRC TAG="159020">心碎一旦透过极限</LRC>
<LRC TAG="162620">有多少岁月</LRC>
<LRC TAG="165220">犹豫和不完全</LRC>
<LRC TAG="169760">我是你无奈的选择</LRC>
<LRC TAG="173210">你只想跟一个好人</LRC>
<LRC TAG="176810">我为你戴上了戒指</LRC>
<LRC TAG="180360">你的笑也还算逼真</LRC>
<LRC TAG="184000">我是你无奈的选择</LRC>
<LRC TAG="187800">却不是多么爱的人</LRC>
<LRC TAG="191450">只怪那下手太残忍</LRC>
<LRC TAG="195000">改变你一生</LRC>
<LRC TAG="199390">我是你无奈的选择</LRC>
<LRC TAG="202440">你只想跟一个好人</LRC>
<LRC TAG="206040">我为你戴上了戒指</LRC>
<LRC TAG="209790">你的笑也还算是那么逼真</LRC>
<LRC TAG="213630">我是你无奈的选择</LRC>
<LRC TAG="216930">却不是多么爱的人</LRC>
<LRC TAG="220580">只怪那下手太残忍</LRC>
<LRC TAG="224030">改变你一生</LRC>
</LYRICS>
</MUSIC>